### PR TITLE
Change mshidkmdf

### PR DESCRIPTION
**Pull request by TheMorc**
*Warning: I don't have a device with a FTS touchscreen so I can't check if this driver is affected by changes in PR.*

I've found out that you can apparently fix all debugging issues, improve responsiveness and fix multitouch on the base vhidmini driver by changing the driver from a two service driver (vhidmini and mshidkmdf) to a single service driver (vhidmini) where the mshidkmdf layer/filter is loaded by a UpperFilter?

(tbh, I really don't know the exact behind the scenes difference but it did the trick for me. I had a really bad time diagnosing this and I looked two days for the issue lol..)

### CODE REVIEW

**Comment by MollySophia** [comment]
Wow!
I don't have a device with FTS touchscreen either, but I think @qaz6750 may have the chance to test this :D

**Comment by qaz6750** [comment]
* The Fts driver seems to rely on mshidkmdf. When I try, touch doesn't work

**Comment by qaz6750** [comment]
* In fact, I once asked the author of the driver, and it told me that I need to pay attention to: probe and irq
* But I still don't know how to change it
* In addition, the right click problem only occurs on MI9/MIX3 5g, Long press -> Multiple clicks

**Comment by TheMorc** [comment]
Didn't mean to close it but you can still find the same pattern in other drivers.

**Pull request closed without merging**
